<?php

declare(strict_types=1);

namespace Fixture\Full;

/**
 * Other
 *
 * A second block, referenced by BlockCoverage.
 *
 * Documentation-only type: at runtime a block is always a \Flyo\Model\Block, and the values these
 * getters return are plain \stdClass objects. Annotate a variable with @var; do not instantiate
 * this class.
 *
 * @generated by flyo/nitro-php - do not edit; regenerate with `vendor/bin/flyo-generate-blocks`.
 */
class BlockOther extends \Flyo\Model\Block
{
    public const IDENTIFIER = 'other';

    public const COMPONENT = 'Other';

    /** @return object{headline: string|null, _empty: bool|null}|null */
    public function getContent()
    {
        /** @var object{headline: string|null, _empty: bool|null}|null */
        return parent::getContent();
    }

    /** @return object{_empty: bool|null}|null */
    public function getConfig()
    {
        /** @var object{_empty: bool|null}|null */
        return parent::getConfig();
    }

    /** @return array<int, \stdClass>|null */
    public function getItems()
    {
        /** @var array<int, \stdClass>|null */
        return parent::getItems();
    }
}
