<?php

declare(strict_types=1);

namespace Fixture\Full;

/**
 * Text
 *
 * Block definition "text" (component: Text). A hint that closes a comment *&#47; and pretends to
 * be a tag &#64;return int and spans several lines, plus enough words after it that the renderer
 * has to wrap and then truncate the whole thing rat…
 *
 * Documentation-only type: at runtime a block is always a \Flyo\Model\Block, and the values these
 * getters return are plain \stdClass objects. Annotate a variable with @var; do not instantiate
 * this class.
 *
 * @generated by flyo/nitro-php - do not edit; regenerate with `vendor/bin/flyo-generate-blocks`.
 */
class BlockText extends \Flyo\Model\Block
{
    public const IDENTIFIER = 'text';

    public const COMPONENT = 'Text';

    /**
     * @return object{
     *     body: object{html: string|null, json: \stdClass|null}|null,
     *     _empty: bool|null
     * }|null
     */
    public function getContent()
    {
        /**
         * @var object{
         *     body: object{html: string|null, json: \stdClass|null}|null,
         *     _empty: bool|null
         * }|null
         */
        return parent::getContent();
    }

    /** @return object{_empty: bool|null}|null */
    public function getConfig()
    {
        /** @var object{_empty: bool|null}|null */
        return parent::getConfig();
    }

    /** @return array<int, \stdClass>|null */
    public function getItems()
    {
        /** @var array<int, \stdClass>|null */
        return parent::getItems();
    }
}
