<?php

declare(strict_types=1);

namespace Fixture\Full;

/**
 * Coverage
 *
 * Block definition "coverage" (component: Coverage). Exercises the type mapper.
 *
 * Declared slots: main, aside.
 *
 * Documentation-only type: at runtime a block is always a \Flyo\Model\Block, and the values these
 * getters return are plain \stdClass objects. Annotate a variable with @var; do not instantiate
 * this class.
 *
 * @generated by flyo/nitro-php - do not edit; regenerate with `vendor/bin/flyo-generate-blocks`.
 */
class BlockCoverage extends \Flyo\Model\Block
{
    public const IDENTIFIER = 'coverage';

    public const COMPONENT = 'Coverage';

    /** @var list<string> */
    public const SLOTS = ['main', 'aside'];

    /**
     * Every leaf shape the server can emit.
     *
     * @return object{
     *     required_string: string,
     *     plain_string: string|null,
     *     an_integer: int|null,
     *     bounded_integer: int<1, 7>|null,
     *     a_number: int|float|null,
     *     a_boolean: bool|null,
     *     nullable_string: string|null,
     *     formatted: string|null,
     *     single_enum: 'only'|null,
     *     multi_enum: 'wide'|'narrow'|'full'|null,
     *     enum_without_type: 'a'|'b'|null,
     *     enum_with_quote: 'it\'s'|'plain'|null,
     *     nested_object: object{deep: object{deeper: string|null}|null}|null,
     *     open_map: \stdClass|null,
     *     string_map: \stdClass|null,
     *     bare_object: \stdClass|null,
     *     object_list: array<int, object{label: string|null, weight: int|float|null}>|null,
     *     scalar_list: array<int, string>|null,
     *     open_map_list: array<int, \stdClass>|null,
     *     untyped_items_list: array<int, mixed>|null,
     *     list_without_items: array<int, mixed>|null,
     *     one_of_int_bool: bool|int|null,
     *     one_of_string_bool: bool|string|null,
     *     any_of_scalars: float|int|string|null,
     *     all_of_merged: object{from_first: string, from_second: int|null}|null,
     *     all_of_unmergeable: mixed,
     *     ref_to_other_block: \Fixture\Full\BlockOther|null,
     *     ref_to_generic_block: \Flyo\Model\Block|null,
     *     ref_dangling: mixed,
     *     ref_to_unmarked: object{name: string|null}|null,
     *     no_type_at_all: mixed,
     *     'my-field': string|null,
     *     'length (cm)': int|float|null,
     *     _empty: bool|null
     * }
     */
    public function getContent()
    {
        /**
         * @var object{
         *     required_string: string,
         *     plain_string: string|null,
         *     an_integer: int|null,
         *     bounded_integer: int<1, 7>|null,
         *     a_number: int|float|null,
         *     a_boolean: bool|null,
         *     nullable_string: string|null,
         *     formatted: string|null,
         *     single_enum: 'only'|null,
         *     multi_enum: 'wide'|'narrow'|'full'|null,
         *     enum_without_type: 'a'|'b'|null,
         *     enum_with_quote: 'it\'s'|'plain'|null,
         *     nested_object: object{deep: object{deeper: string|null}|null}|null,
         *     open_map: \stdClass|null,
         *     string_map: \stdClass|null,
         *     bare_object: \stdClass|null,
         *     object_list: array<int, object{label: string|null, weight: int|float|null}>|null,
         *     scalar_list: array<int, string>|null,
         *     open_map_list: array<int, \stdClass>|null,
         *     untyped_items_list: array<int, mixed>|null,
         *     list_without_items: array<int, mixed>|null,
         *     one_of_int_bool: bool|int|null,
         *     one_of_string_bool: bool|string|null,
         *     any_of_scalars: float|int|string|null,
         *     all_of_merged: object{from_first: string, from_second: int|null}|null,
         *     all_of_unmergeable: mixed,
         *     ref_to_other_block: \Fixture\Full\BlockOther|null,
         *     ref_to_generic_block: \Flyo\Model\Block|null,
         *     ref_dangling: mixed,
         *     ref_to_unmarked: object{name: string|null}|null,
         *     no_type_at_all: mixed,
         *     'my-field': string|null,
         *     'length (cm)': int|float|null,
         *     _empty: bool|null
         * }
         */
        return parent::getContent();
    }

    /**
     * Block configuration fields.
     *
     * @return object{_empty: bool|null}|null
     */
    public function getConfig()
    {
        /** @var object{_empty: bool|null}|null */
        return parent::getConfig();
    }

    /**
     * Iterated content pool items mapped to block fields.
     *
     * @return array<int, object{
     *     link: object{
     *         entity_unique_id: string|null,
     *         entity_type_id: bool|int|null,
     *         routes: \stdClass|null
     *     }|null
     * }>|null
     */
    public function getItems()
    {
        /**
         * @var array<int, object{
         *     link: object{
         *         entity_unique_id: string|null,
         *         entity_type_id: bool|int|null,
         *         routes: \stdClass|null
         *     }|null
         * }>|null
         */
        return parent::getItems();
    }
}
