<?php

declare(strict_types=1);

namespace Fixture\Site\Entities;

/**
 * Events
 *
 * Entity model for "Events" (Schema ID: 2).
 *
 * Documentation-only type: at runtime an entity is always a \Flyo\Model\Entity, and getModel()
 * returns a plain \stdClass object. Annotate a variable with @var; do not instantiate this class.
 *
 * @generated by flyo/nitro-php - do not edit; regenerate with `vendor/bin/flyo-generate-types`.
 */
class EntityEvent extends \Flyo\Model\Entity
{
    /**
     * @return object{
     *     starts_at: int|null,
     *     tickets: string|null,
     *     sold_out: bool|null,
     *     venue: object{
     *         zip: int|float|null,
     *         city: string|null,
     *         cords_lat: int|float|null
     *     }|null
     * }|null
     */
    public function getModel()
    {
        /**
         * @var object{
         *     starts_at: int|null,
         *     tickets: string|null,
         *     sold_out: bool|null,
         *     venue: object{
         *         zip: int|float|null,
         *         city: string|null,
         *         cords_lat: int|float|null
         *     }|null
         * }|null
         */
        return parent::getModel();
    }
}
