<?php

declare(strict_types=1);

namespace Fixture\Site\Entities;

/**
 * Articles
 *
 * Entity model for "Articles" (Schema ID: 1).
 *
 * Documentation-only type: at runtime an entity is always a \Flyo\Model\Entity, and getModel()
 * returns a plain \stdClass object. Annotate a variable with @var; do not instantiate this class.
 *
 * @generated by flyo/nitro-php - do not edit; regenerate with `vendor/bin/flyo-generate-types`.
 */
class EntityArticle extends \Flyo\Model\Entity
{
    /**
     * @return object{
     *     headline: string|null,
     *     published_at: int|null,
     *     image: object{
     *         source: string|null,
     *         caption: string|null,
     *         id: int|float|null
     *     }|null,
     *     content: object{html: string|null, json: \stdClass|null}|null,
     *     category: object{
     *         value: 'news'|'report'|null,
     *         options: \stdClass|null,
     *         label: string|null
     *     }|null,
     *     tags: object{
     *         topics: array<int, object{title: string|null, slug: string|null}>|null
     *     }|null,
     *     events: array<int, object{id: int|float|null, unique_id: string|null}>|null
     * }|null
     */
    public function getModel()
    {
        /**
         * @var object{
         *     headline: string|null,
         *     published_at: int|null,
         *     image: object{
         *         source: string|null,
         *         caption: string|null,
         *         id: int|float|null
         *     }|null,
         *     content: object{html: string|null, json: \stdClass|null}|null,
         *     category: object{
         *         value: 'news'|'report'|null,
         *         options: \stdClass|null,
         *         label: string|null
         *     }|null,
         *     tags: object{
         *         topics: array<int, object{title: string|null, slug: string|null}>|null
         *     }|null,
         *     events: array<int, object{id: int|float|null, unique_id: string|null}>|null
         * }|null
         */
        return parent::getModel();
    }
}
