<?php

declare(strict_types=1);

namespace Fixture\Site\Containers;

/**
 * Main navigation
 *
 * Navigation container "Main navigation", as delivered under `containers.main`.
 *
 * Documentation-only type: at runtime a container is always a
 * \Flyo\Model\ConfigResponseContainersValue, found under its IDENTIFIER in
 * ConfigResponse::getContainers(). Annotate a variable with @var; do not instantiate this class.
 *
 * @generated by flyo/nitro-php - do not edit; regenerate with `vendor/bin/flyo-generate-types`.
 */
class ContainerMain extends \Flyo\Model\ConfigResponseContainersValue
{
    public const IDENTIFIER = 'main';

    /**
     * The pages of this container, as a tree.
     *
     * @return array<int, \Fixture\Site\Containers\ContainerItem>
     */
    public function getItems()
    {
        /** @var array<int, \Fixture\Site\Containers\ContainerItem> */
        return parent::getItems();
    }
}
