<?php

declare(strict_types=1);

namespace Fixture\Site\Containers;

/**
 * Container Item
 *
 * One entry of a navigation container. Carries no x-schema-type: it is generated because the
 * containers reference it.
 *
 * Documentation-only type: at runtime a container item is always a \Flyo\Model\ContainerPage, and
 * getProperties() returns a plain array of decoded values. Annotate a variable with @var; do not
 * instantiate this class.
 *
 * @generated by flyo/nitro-php - do not edit; regenerate with `vendor/bin/flyo-generate-types`.
 */
class ContainerItem extends \Flyo\Model\ContainerPage
{
    /**
     * The page properties this site made available to the navigation.
     *
     * @return array{
     *     icon: string|null,
     *     highlight: bool|null,
     *     'teaser-image': object{source: string|null, caption: string|null}|null
     * }
     */
    public function getProperties()
    {
        /**
         * @var array{
         *     icon: string|null,
         *     highlight: bool|null,
         *     'teaser-image': object{source: string|null, caption: string|null}|null
         * }
         */
        return parent::getProperties();
    }

    /**
     * The entries below this one, empty when there are none.
     *
     * @return array<int, \Fixture\Site\Containers\ContainerItem>
     */
    public function getChildren()
    {
        /** @var array<int, \Fixture\Site\Containers\ContainerItem> */
        return parent::getChildren();
    }
}
