<?php

declare(strict_types=1);

namespace Fixture\Site\Containers;

/**
 * Footer
 *
 * Navigation container "Footer", as delivered under `containers.footer`.
 *
 * Documentation-only type: at runtime a container is always a
 * \Flyo\Model\ConfigResponseContainersValue, found under its IDENTIFIER in
 * ConfigResponse::getContainers(). Annotate a variable with @var; do not instantiate this class.
 *
 * @generated by flyo/nitro-php - do not edit; regenerate with `vendor/bin/flyo-generate-types`.
 */
class ContainerFooter extends \Flyo\Model\ConfigResponseContainersValue
{
    public const IDENTIFIER = 'footer';

    /** @return array<int, \Fixture\Site\Containers\ContainerItem> */
    public function getItems()
    {
        /** @var array<int, \Fixture\Site\Containers\ContainerItem> */
        return parent::getItems();
    }
}
