<?php

declare(strict_types=1);

namespace Fixture\Site\Blocks;

/**
 * Teaser
 *
 * Block definition "teaser" (component: Teaser).
 *
 * Declared slots: aside.
 *
 * Documentation-only type: at runtime a block is always a \Flyo\Model\Block, and the values these
 * getters return are plain \stdClass objects. Annotate a variable with @var; do not instantiate
 * this class.
 *
 * @generated by flyo/nitro-php - do not edit; regenerate with `vendor/bin/flyo-generate-types`.
 */
class BlockTeaser extends \Flyo\Model\Block
{
    public const IDENTIFIER = 'teaser';

    public const COMPONENT = 'Teaser';

    /** @var list<string> */
    public const SLOTS = ['aside'];

    /**
     * Block content fields.
     *
     * @return object{
     *     title: string,
     *     image: object{source: string|null, caption: string|null}|null,
     *     _empty: bool|null
     * }
     */
    public function getContent()
    {
        /**
         * @var object{
         *     title: string,
         *     image: object{source: string|null, caption: string|null}|null,
         *     _empty: bool|null
         * }
         */
        return parent::getContent();
    }

    /**
     * Block configuration fields.
     *
     * @return object{dark: bool|null, _empty: bool|null}
     */
    public function getConfig()
    {
        /** @var object{dark: bool|null, _empty: bool|null} */
        return parent::getConfig();
    }

    /**
     * Iterated content pool items mapped to block fields.
     *
     * @return array<int, object{
     *     title: mixed,
     *     link: object{entity_slug: string|null, routes: \stdClass|null}|null
     * }>
     */
    public function getItems()
    {
        /**
         * @var array<int, object{
         *     title: mixed,
         *     link: object{entity_slug: string|null, routes: \stdClass|null}|null
         * }>
         */
        return parent::getItems();
    }
}
