<?php

declare(strict_types=1);

namespace Fixture\Collisions;

/**
 * Hero Banner
 *
 * Component with a space.
 *
 * Documentation-only type: at runtime a block is always a \Flyo\Model\Block, and the values these
 * getters return are plain \stdClass objects. Annotate a variable with @var; do not instantiate
 * this class.
 *
 * @generated by flyo/nitro-php - do not edit; regenerate with `vendor/bin/flyo-generate-blocks`.
 */
class BlockHeroBanner extends \Flyo\Model\Block
{
    public const IDENTIFIER = 'hero_banner_spaced';

    public const COMPONENT = 'Hero Banner';

    /** @return object{_empty: bool|null}|null */
    public function getContent()
    {
        /** @var object{_empty: bool|null}|null */
        return parent::getContent();
    }

    /** @return object{_empty: bool|null}|null */
    public function getConfig()
    {
        /** @var object{_empty: bool|null}|null */
        return parent::getConfig();
    }

    /** @return array<int, \stdClass>|null */
    public function getItems()
    {
        /** @var array<int, \stdClass>|null */
        return parent::getItems();
    }
}
