<?php

declare(strict_types=1);

namespace Flyo\Blocks\Generator;

/**
 * Renders a {@see ClassDef} as PHP source.
 *
 * Pure and deterministic: no timestamp, no version, no source URL, nothing else that would churn
 * the output between runs on identical input. Emits stock PSR-12 rather than this repository's own
 * cs-fixer dialect, because the files land in the consumer's repository, where a stock fixer would
 * otherwise reformat what the next run reverts.
 */
final class Renderer
{
    /** Exactly this string identifies a file as ours, for stale-file cleanup. */
    public const MARKER = '@generated by flyo/nitro-php';

    /** The SDK model every generated class extends. */
    public const PARENT_CLASS = '\Flyo\Model\Block';

    private const EOL = "\n";

    private const INDENT = '    ';

    /** Descriptions come from author-supplied labels and hints, so they get a sane ceiling. */
    private const MAX_TEXT = 240;

    private const WRAP = 96;

    public function render(ClassDef $class): string
    {
        $lines = [
            '<?php',
            '',
            'declare(strict_types=1);',
            '',
            'namespace ' . $class->namespace . ';',
            '',
        ];

        $lines = [...$lines, ...$this->classDocblock($class)];
        $lines[] = 'class ' . $class->className . ' extends ' . self::PARENT_CLASS;
        $lines[] = '{';
        $lines = [...$lines, ...$this->constants($class)];

        foreach ($class->methods as $index => $method) {
            if ($index > 0 || $class->identifier !== '' || $class->component !== '' || $class->slots !== []) {
                $lines[] = '';
            }

            $lines = [...$lines, ...$this->method($method)];
        }

        $lines[] = '}';

        return implode(self::EOL, $lines) . self::EOL;
    }

    /**
     * @return list<string>
     */
    private function classDocblock(ClassDef $class): array
    {
        $body = [];

        $title = self::sanitize($class->title);
        if ($title !== '') {
            $body[] = $title;
        }

        $description = self::sanitize($class->description);
        if ($description !== '' && $description !== $title) {
            if ($body !== []) {
                $body[] = '';
            }

            $body = [...$body, ...self::wrap($description)];
        }

        if ($class->slots !== []) {
            $body[] = '';
            $body = [...$body, ...self::wrap('Declared slots: ' . implode(', ', $class->slots) . '.')];
        }

        if ($body !== []) {
            $body[] = '';
        }

        $body = [...$body, ...self::wrap(
            'Documentation-only type: at runtime a block is always a ' . self::PARENT_CLASS
                . ', and the values these getters return are plain \stdClass objects. Annotate a '
                . 'variable with @var; do not instantiate this class.'
        )];

        $body[] = '';
        $body = [...$body, ...self::wrap(
            self::MARKER . ' - do not edit; regenerate with `vendor/bin/flyo-generate-blocks`.'
        )];

        return self::docblock($body, '');
    }

    /**
     * @return list<string>
     */
    private function constants(ClassDef $class): array
    {
        $lines = [];

        if ($class->identifier !== '') {
            $lines[] = self::INDENT . 'public const IDENTIFIER = ' . self::literal($class->identifier) . ';';
        }

        if ($class->component !== '') {
            if ($lines !== []) {
                $lines[] = '';
            }

            $lines[] = self::INDENT . 'public const COMPONENT = ' . self::literal($class->component) . ';';
        }

        if ($class->slots !== []) {
            if ($lines !== []) {
                $lines[] = '';
            }

            $values = array_map(static fn (string $slot): string => self::literal($slot), $class->slots);

            $lines[] = self::INDENT . '/** @var list<string> */';
            $lines[] = self::INDENT . 'public const SLOTS = [' . implode(', ', $values) . '];';
        }

        return $lines;
    }

    /**
     * @return list<string>
     */
    private function method(MethodDef $method): array
    {
        $body = [];

        $description = self::sanitize($method->description);
        if ($description !== '') {
            $body = [...self::wrap($description), ''];
        }

        $body = [...$body, ...self::typeTag('@return', $method->type)];

        $lines = self::docblock($body, self::INDENT);
        $lines[] = self::INDENT . 'public function ' . $method->name . '()';
        $lines[] = self::INDENT . '{';

        // The narrow type again, on the return statement. Without it PHPStan reports
        // "should return object{...} but returns object|null" from level 7 up, because narrowing
        // the signature does not narrow the parent getter's own return type.
        $lines = [
            ...$lines,
            ...self::docblock(self::typeTag('@var', $method->type), self::INDENT . self::INDENT),
        ];

        $lines[] = self::INDENT . self::INDENT . 'return parent::' . $method->name . '();';
        $lines[] = self::INDENT . '}';

        return $lines;
    }

    /**
     * A phpdoc tag whose type may span several lines, with the type's own indentation preserved.
     *
     * @return list<string>
     */
    private static function typeTag(string $tag, string $type): array
    {
        $typeLines = explode(self::EOL, $type);
        $lines = [$tag . ' ' . array_shift($typeLines)];

        foreach ($typeLines as $line) {
            $lines[] = $line;
        }

        return $lines;
    }

    /**
     * Wraps body lines in a docblock, collapsing to a one-liner when it fits.
     *
     * @param list<string> $body
     * @return list<string>
     */
    private static function docblock(array $body, string $indent): array
    {
        if ($body === []) {
            return [];
        }

        if (count($body) === 1 && $body[0] !== '' && !str_contains($body[0], '*/')) {
            $oneLine = $indent . '/** ' . $body[0] . ' */';

            if (mb_strlen($oneLine) <= self::WRAP + mb_strlen($indent)) {
                return [$oneLine];
            }
        }

        $lines = [$indent . '/**'];

        foreach ($body as $line) {
            $lines[] = $line === '' ? rtrim($indent . ' *') : $indent . ' * ' . $line;
        }

        $lines[] = $indent . ' */';

        return $lines;
    }

    /**
     * @return list<string>
     */
    private static function wrap(string $text): array
    {
        if ($text === '') {
            return [];
        }

        return explode(self::EOL, wordwrap($text, self::WRAP, self::EOL, false));
    }

    /**
     * Makes author-supplied text safe inside a docblock.
     *
     * Labels and hints are free text, so they can close the comment, span lines, or look like a
     * phpdoc tag. All three would produce a broken or misleading file.
     */
    private static function sanitize(string $text, int $max = self::MAX_TEXT): string
    {
        if ($text === '' || !mb_check_encoding($text, 'UTF-8')) {
            return '';
        }

        $text = preg_replace('/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/u', '', $text) ?? '';
        $text = str_replace('*/', '*&#47;', $text);
        $text = preg_replace('/\s+/u', ' ', $text) ?? '';
        $text = trim($text);
        $text = preg_replace('/(^|\s)@/u', '$1&#64;', $text) ?? '';

        if (mb_strlen($text) > $max) {
            $text = rtrim(mb_substr($text, 0, $max - 1)) . '…';
        }

        return $text;
    }

    private static function literal(string $value): string
    {
        return "'" . str_replace(['\\', "'"], ['\\\\', "\\'"], $value) . "'";
    }
}
