<?php

declare(strict_types=1);

namespace Fixture\Hero;

/**
 * Hero
 *
 * Block definition "hero" (component: Hero). Grossflächiger Einstiegsbereich mit Titel, Text,
 * Bild und Link.
 *
 * Documentation-only type: at runtime a block is always a \Flyo\Model\Block, and the values these
 * getters return are plain \stdClass objects. Annotate a variable with @var; do not instantiate
 * this class.
 *
 * @generated by flyo/nitro-php - do not edit; regenerate with `vendor/bin/flyo-generate-blocks`.
 */
class BlockHero extends \Flyo\Model\Block
{
    public const IDENTIFIER = 'hero';

    public const COMPONENT = 'Hero';

    /**
     * Grossflächiger Einstiegsbereich mit Titel, Text, Bild und Link.
     *
     * @return object{
     *     title: string|null,
     *     text: string|null,
     *     image: object{
     *         source: string|null,
     *         caption: string|null,
     *         copyright: string|null,
     *         name: string|null,
     *         id: int|float|null,
     *         mime_type: string|null
     *     }|null,
     *     link: object{
     *         type: string|null,
     *         target: string|null,
     *         raw: string|null,
     *         href: string|null,
     *         extras: \stdClass|null
     *     }|null,
     *     _empty: bool|null
     * }|null
     */
    public function getContent()
    {
        /**
         * @var object{
         *     title: string|null,
         *     text: string|null,
         *     image: object{
         *         source: string|null,
         *         caption: string|null,
         *         copyright: string|null,
         *         name: string|null,
         *         id: int|float|null,
         *         mime_type: string|null
         *     }|null,
         *     link: object{
         *         type: string|null,
         *         target: string|null,
         *         raw: string|null,
         *         href: string|null,
         *         extras: \stdClass|null
         *     }|null,
         *     _empty: bool|null
         * }|null
         */
        return parent::getContent();
    }

    /**
     * Block configuration fields.
     *
     * @return object{_empty: bool|null}|null
     */
    public function getConfig()
    {
        /** @var object{_empty: bool|null}|null */
        return parent::getConfig();
    }

    /**
     * Iterated content pool items mapped to block fields.
     *
     * @return array<int, object{
     *     link: object{
     *         entity_unique_id: string|null,
     *         entity_slug: string|null,
     *         entity_type_id: bool|int|null,
     *         routes: \stdClass|null
     *     }|null
     * }>|null
     */
    public function getItems()
    {
        /**
         * @var array<int, object{
         *     link: object{
         *         entity_unique_id: string|null,
         *         entity_slug: string|null,
         *         entity_type_id: bool|int|null,
         *         routes: \stdClass|null
         *     }|null
         * }>|null
         */
        return parent::getItems();
    }
}
